#!/system/bin/sh
# Consolidated T5UN4MI Script
# PrimeDirective, Sonicxml, DHO, Nuclearmistake
# With inspiration from DroidTh3ory

sync
sysrw

#
# Enable Sysctl Tweaks
#
sysctl -p /system/etc/sysctl.conf

#RQ_Affinity
for b in /sys/block/*; do echo 1 > $b/queue/rq_affinity; done

#
#
# Sysctl & VM Tweaks
#
busybox sysctl -w vm.page-cluster=3
busybox sysctl -w vm.drop_caches=3
busybox sysctl -w vm.dirty_expire_centisecs=1750
busybox sysctl -w vm.dirty_writeback_centisecs=3200
busybox sysctl -w kernel.random.write_wakeup_threshold=256
busybox sysctl -w kernel.random.read_wakeup_threshold=128
busybox sysctl -w fs.file-max=524288
busybox sysctl -w fs.inotify.max_queued_events=32000
busybox sysctl -w kernel.panic=0
busybox sysctl -w kernel.panic_on_oops=1
busybox sysctl -w kernel.msgmni=2048
busybox sysctl -w kernel.msgmax=64000
busybox sysctl -w kernel.shmmax=268435500
busybox sysctl -w kernel.sem=500,512000,64,2048
busybox sysctl -w kernel.threads-max=525810
echo "1" > /proc/sys/vm/laptop_mode
rm /dev/log/main

# Vibration
echo "1650" /sys/class/misc/vibratorcontrol/vibrator_strength

#Deep Sleep
#
echo 6 > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_cpulevel
echo 2 > /sys/devices/system/cpu/cpu0/cpufreq/deepsleep_buslevel

LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;
for j in $LOOP $RAM
do
echo 0 > $j/queue/rotational;
echo 1024 > $j/queue/read_ahead_kb;
done

#
# START wrapper script that brute-forces rngd until it stays alive
#
####
rngd

#
# File System Tweaks & Cleanup
#
for m in "/" "/dev" "/proc" "/sys" "/system" "/data" "/data/data" "/cache" "/acct" "/dev/pts" "/dev/cpuctl" "/mnt/asec" "/mnt/obb"; do
  busybox mount -o remount,noatime,nodiratime,discard,noauto_da_alloc,nodev $m
done

echo "10" > /proc/sys/fs/lease-break-time

sync
sysro
