#!/system/bin/sh
# Consolidated T5UN4MI Script
# PrimeDirective, Sonicxml, DHO, Nuclearmistake
# With inspiration from DroidTh3ory

sync
sysrw

#
# Enable Sysctl Tweaks
#
sysctl -p /system/etc/sysctl.conf

#RQ_Affinity
for b in /sys/block/*; do echo 1 > $b/queue/rq_affinity; done

# rm /dev/log/main

# Enable Dynamic Sync
echo "1" /sys/kernel/dyn_fsync/Dyn_fsync_active

# Vibration
echo "1650" /sys/class/misc/vibratorcontrol/vibrator_strength

LOOP=`ls -d /sys/block/loop*`;
RAM=`ls -d /sys/block/ram*`;
MMC=`ls -d /sys/block/mmc*`;
for j in $LOOP $RAM
do
echo 0 > $j/queue/rotational;
echo 1024 > $j/queue/read_ahead_kb;
done

sync
sysro
