#!/system/bin/sh

mount -o remount,rw /cache

if [ ! -e /cache/swap.img ]
then 
dd if=/dev/zero of=/cache/swap.img bs=1024 count=200000
fi 

busybox losetup /dev/block/loop7 /cache/swap.img
busybox mkswap /dev/block/loop7
busybox swapon /dev/block/loop7
