#!/system/bin/sh
busybox=/system/xbin/busybox
fstrim=/system/bin/fstrim
trimhelper=/data/trimhelper

# initialize suspend trim helper

if [ -s /data/trimhelper ] ; then
  $busybox sed -i "1s/.*/$($busybox date +%s)/" $trimhelper
else
  $busybox date +%s > $trimhelper
  $busybox echo 0 >> $trimhelper
fi

# trim file system if wipes have been performed
if [ ! -e /cache/trimmed ] ; then
  $fstrim /cache
  $busybox touch /cache/trimmed
fi

if [ ! -e /data/dalvik-cache/trimmed ] ; then
  $busybox mount -o remount,nodiscard /data
  $fstrim /data
  $busybox mount -o remount,discard /data
  $busybox touch /data/dalvik-cache/trimmed
fi
